# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Paw < Formula
  desc "A project management system built on Claude Code"
  homepage "https://github.com/dongho-jung/paw"
  version "0.9.2"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dongho-jung/paw/releases/download/v0.9.2/paw_0.9.2_darwin_amd64.tar.gz"
      sha256 "d1e73fdb915602ef5c1c3dcdb6874e8ea3ad90fdd6487d87acbdc53d037b77df"

      def install
        bin.install "paw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dongho-jung/paw/releases/download/v0.9.2/paw_0.9.2_darwin_arm64.tar.gz"
      sha256 "328a25ece118dd378365b0b551eaf70bf0fabbe5be8f9050da444399040414aa"

      def install
        bin.install "paw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dongho-jung/paw/releases/download/v0.9.2/paw_0.9.2_linux_amd64.tar.gz"
      sha256 "1bf6a2e08de6cb02302077888d3fc4bdc54dc8f5c630be956ec5a1889c9e6ae5"
      def install
        bin.install "paw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dongho-jung/paw/releases/download/v0.9.2/paw_0.9.2_linux_arm64.tar.gz"
      sha256 "19350d6ce52f7fd1e416be61dac7d3d41d9652f370c446958e659564f695f6d5"
      def install
        bin.install "paw"
      end
    end
  end

  test do
    system "#{bin}/paw", "version"
  end
end
