# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Paw < Formula
  desc "A project management system built on Claude Code"
  homepage "https://github.com/dongho-jung/paw"
  version "0.4.2"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dongho-jung/paw/releases/download/v0.4.2/paw_0.4.2_darwin_amd64.tar.gz"
      sha256 "98c41e0138917c9fa2493ee8ec1c266bb42db1f5a05d4bfa23ab0551aadc7764"

      def install
        bin.install "paw"
        # Install paw-notify.app for macOS desktop notifications
        if File.exist?("paw-notify.app")
          (share/"paw").install "paw-notify.app"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dongho-jung/paw/releases/download/v0.4.2/paw_0.4.2_darwin_arm64.tar.gz"
      sha256 "c888ae5dbf62bcdc07675e0a6f0ee6610cb9f8b275b35da780f3ca264e5ca672"

      def install
        bin.install "paw"
        # Install paw-notify.app for macOS desktop notifications
        if File.exist?("paw-notify.app")
          (share/"paw").install "paw-notify.app"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dongho-jung/paw/releases/download/v0.4.2/paw_0.4.2_linux_amd64.tar.gz"
      sha256 "caf2eac2b17ea76da6f42e0a1c182dd8c81dff23bfb04c6bd9b3c985986ff6e6"
      def install
        bin.install "paw"
        # Install paw-notify.app for macOS desktop notifications
        if File.exist?("paw-notify.app")
          (share/"paw").install "paw-notify.app"
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dongho-jung/paw/releases/download/v0.4.2/paw_0.4.2_linux_arm64.tar.gz"
      sha256 "0f9becea436ad47719a82d73092e644064aa68858c4d7d6cc744731c032d3685"
      def install
        bin.install "paw"
        # Install paw-notify.app for macOS desktop notifications
        if File.exist?("paw-notify.app")
          (share/"paw").install "paw-notify.app"
        end
      end
    end
  end

  def post_install
    # Copy paw-notify.app to user's local share directory
    if File.exist?("#{share}/paw/paw-notify.app")
      user_share = "#{ENV["HOME"]}/.local/share/paw"
      mkdir_p user_share unless File.directory?(user_share)
      system "rm", "-rf", "#{user_share}/paw-notify.app"
      system "cp", "-R", "#{share}/paw/paw-notify.app", user_share
      # Remove quarantine attribute and sign
      system "xattr", "-cr", "#{user_share}/paw-notify.app"
      system "codesign", "-fs", "-", "#{user_share}/paw-notify.app"
    end
  end

  def caveats
    <<~EOS
      paw-notify.app has been installed to ~/.local/share/paw/

      To enable desktop notifications, you may need to:
      1. Run: paw check
      2. Grant notification permissions when prompted
    EOS
  end

  test do
    system "#{bin}/paw", "version"
  end
end
