# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Paw < Formula
  desc "A project management system built on Claude Code"
  homepage "https://github.com/dongho-jung/paw"
  version "0.2.5"
  license "MIT"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dongho-jung/paw/releases/download/v0.2.5/paw_0.2.5_darwin_amd64.tar.gz"
      sha256 "a0ceaf924749ac774df84de4443f0f9925fb500d81d9ee2359b8d862d341aa4a"

      def install
        bin.install "paw"
        # Install paw-notify.app for macOS desktop notifications
        if File.exist?("paw-notify.app")
          (share/"paw").install "paw-notify.app"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dongho-jung/paw/releases/download/v0.2.5/paw_0.2.5_darwin_arm64.tar.gz"
      sha256 "8ae551ecef9b90668f1c5d9906677e9335d4074a4409fd250a0039df2645efd7"

      def install
        bin.install "paw"
        # Install paw-notify.app for macOS desktop notifications
        if File.exist?("paw-notify.app")
          (share/"paw").install "paw-notify.app"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dongho-jung/paw/releases/download/v0.2.5/paw_0.2.5_linux_amd64.tar.gz"
      sha256 "5ffb3d1ddab37a2e9c37966c13c7d7ca1c4ad7b77742c957416625736a2f2bf7"
      def install
        bin.install "paw"
        # Install paw-notify.app for macOS desktop notifications
        if File.exist?("paw-notify.app")
          (share/"paw").install "paw-notify.app"
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dongho-jung/paw/releases/download/v0.2.5/paw_0.2.5_linux_arm64.tar.gz"
      sha256 "b2cd9d98464788b115f5991d9a45f4da70fcb1af210fe455c271bfc19084386d"
      def install
        bin.install "paw"
        # Install paw-notify.app for macOS desktop notifications
        if File.exist?("paw-notify.app")
          (share/"paw").install "paw-notify.app"
        end
      end
    end
  end

  def post_install
    # Copy paw-notify.app to user's local share directory
    if File.exist?("#{share}/paw/paw-notify.app")
      user_share = "#{ENV["HOME"]}/.local/share/paw"
      mkdir_p user_share unless File.directory?(user_share)
      system "rm", "-rf", "#{user_share}/paw-notify.app"
      system "cp", "-R", "#{share}/paw/paw-notify.app", user_share
      # Remove quarantine attribute and sign
      system "xattr", "-cr", "#{user_share}/paw-notify.app"
      system "codesign", "-fs", "-", "#{user_share}/paw-notify.app"
    end
  end

  def caveats
    <<~EOS
      paw-notify.app has been installed to ~/.local/share/paw/

      To enable desktop notifications, you may need to:
      1. Run: paw check
      2. Grant notification permissions when prompted
    EOS
  end

  test do
    system "#{bin}/paw", "version"
  end
end
